### PR TITLE
Run `brew style --fix` to update deprecated syntax

### LINKED ISSUE #187: Deprecated warnings for aws-sam-cli
I've started getting the following whenever I run `brew upgrade`:

```
Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli.rb:19

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli.rb:20

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli.rb:21
```

### PR DESCRIPTION
**Pull request by StormPooper**
*Issue #, if available:*
Closes #187 

*Description of changes:*
Forked the repo and ran `brew style --fix Formula` from the root. There are a further 9 offences the tool did not auto-fix, but I was hesitant to make any further changes as it already altered more than I expected. The `bottle do` block is the important change, so if the other lint changes are not required I can alter this to just change that block. Running the command on my local tap removes the warnings, but I'm unfamiliar with the changes the tool made so this will probably need further testing.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by a-27m — APPROVED** [review]
Looks good to me, a non-maintainer.

**Comment by jfuss** [comment]
@StormPooper Thanks for contributing this. I need to do some further validation before we approve: 
1. Test installation as a sanity check on linux with new and old version of homebrew 
2. Test installation as a sanity check on mac with new and old version of homebrew
3. check our release scripts we have to make sure this doesn't break that accidentally (it shouldn't but rather be cautious). 

I have a couple other prioritizes I am working through right now but plan to get to this later today.

**Comment by StormPooper** [comment]
Sounds good, thanks @jfuss.

**Comment by jfuss** [comment]
Giving an update here. 

I tested on both mac and linux from @StormPooper fork. Everything seems fine there. I started to just very our bottle building is unaffected (I assume not but once we approve this is released so verifying). It's likely I won't get through all of that today (running linux now).

Still digging through our release scripts to verify that is good.

Sorry this is taking a little longer than I originally thought.

**Comment by jfuss** [comment]
Ok Linux bottle building works as expected. Starting the mac verification.

**Comment by jfuss** [comment]
Everything looks good. Given its later on Friday and a merge will directly affect customers, I will merge this in on Monday morning.

To just document what I validated:
* installed on linux (docker container) and mac from StormPooper's tap
* build bottles for linux and mac from StormPooper's tap
* installed bottles generated on linux and mac from StormPooper's tap
* Verified that our release scripts do not touch the formula's (only the json files).

**Comment by StormPooper** [comment]
Great news, thanks @jfuss. Enjoy your weekend 😃

**Comment by Flyraty** [comment]
when run `brew style --fix Formula`，occured  some errors
```sh
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/msgpack-1.4.2/ext/msgpack
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20210515-86692-5r0fnd.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

Gem files will remain installed in /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/msgpack-1.4.2 for inspection.
Results logged to /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-20/2.6.0/msgpack-1.4.2/gem_make.out

An error occurred while installing msgpack (1.4.2), and Bundler cannot continue.
Make sure that `gem install msgpack -v '1.4.2' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  bootsnap was resolved to 1.7.5, which depends on
    msgpack


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/byebug-11.1.3/ext/byebug
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20210515-86692-1vnucta.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

Gem files will remain installed in /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/byebug-11.1.3 for inspection.
Results logged to /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-20/2.6.0/byebug-11.1.3/gem_make.out

An error occurred while installing byebug (11.1.3), and Bundler cannot continue.
Make sure that `gem install byebug -v '11.1.3' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  byebug


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/unf_ext-0.0.7.7/ext/unf_ext
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20210515-86692-41v117.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

Gem files will remain installed in /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/unf_ext-0.0.7.7 for inspection.
Results logged to /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-20/2.6.0/unf_ext-0.0.7.7/gem_make.out

An error occurred while installing unf_ext (0.0.7.7), and Bundler cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.7' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  mechanize was resolved to 2.8.1, which depends on
    http-cookie was resolved to 1.0.3, which depends on
      domain_name was resolved to 0.5.20190701, which depends on
        unf was resolved to 0.1.4, which depends on
          unf_ext


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/hpricot-0.8.6/ext/fast_xs
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20210515-86692-1td1laz.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

Gem files will remain installed in /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/hpricot-0.8.6 for inspection.
Results logged to /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-20/2.6.0/hpricot-0.8.6/gem_make.out

An error occurred while installing hpricot (0.8.6), and Bundler cannot continue.
Make sure that `gem install hpricot -v '0.8.6' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  ronn was resolved to 0.7.3, which depends on
    hpricot
Error: failed to run `/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/bundle install`!

```

**Comment by runfjj** [comment]
For resolving Ruby error, you could refer to the link to install XCode. Then, you could clone this repo and execute "brew style --fix <Repo_Formule_Path>"
https://github.com/CocoaPods/CocoaPods/issues/10286

Reference Steps:
Download Command Line Tools 11.5 from Apple Developer Downloads
sudo rm -rf /Library/Developer/CommandLineTools
Install Command Line Tools from .dmg/.pkg
sudo xcode-select --switch /Library/Developer/CommandLineTools
[sudo] gem install [--user-install] cocoapods
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

**Pull request merged**
