### PR TITLE
rm(flag): remove bottles being un-needed

### PR DESCRIPTION
**Pull request by TheSriram**
- This blocks creation of bottles if not removed.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jfuss** [comment]
@TheSriram Will this affect anything (installations, etc) when we remove it? I am wondering if there is a case in which, removing this would cause `brew install aws-sam-cli` to fail. My understanding is that it wouldn't but just wanted to double check.

**Comment by TheSriram** [comment]
@jfuss it wouldn't, I did a local check by manually modyfying the tap formula and it works as expected.

**Comment by sanathkr** [comment]
Will this work with LinuxBrew as well?

**Comment by TheSriram** [comment]
@sanathkr Yes, this should work on linuxbrew as well. I tested it on a linuxbrew docker container with this change made to the formula.

**Pull request merged**
